[phases.setup]
nixPkgs = ["python312", "ffmpeg", "libopus", "libsodium"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[variables]
PATH = "/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[start]
cmd = "python main.py"