[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["ffmpeg", "libopus", "python312"]

[deploy]
startCommand = "python main.py"
restartPolicyType = "on_failure"
